### ISSUE TITLE
java.lang.InstantiationError: scala.collection.immutable.Vector

### ISSUE THREAD

**Issue by michaelzg** [altoo-ag/scala-kryo-serialization#19]
Hi, I encountered the following stack trace. I have recreated a simplified reproducer using the latest `1.2.0` version of `scala-kryo-serialization`, and I've provided relevant snippets below. But you can see the full repository here: https://github.com/michaelzg/kryo-serialization-issue

Run in `sbt` with cross-built Scala 2.13.x versions. I tested on both Java 11 and 17:
  * `++2.13.15 run` (latest Scala version as of this writing, error is present)
  * `++2.13.2 run` (error is present, also coincidentally [introduced new Vector implementation](https://github.com/scala/scala/releases/tag/v2.13.2))
  * `++2.13.1 run` (no error!)

Also, behavior varies with [`id-strategy` configuration](https://github.com/altoo-ag/scala-kryo-serialization/blob/main/core/src/main/resources/reference.conf#L34):
  * incremental - `works on all three scala versions`
  * automatic - `java.lang.InstantiationError`
  * default - `java.lang.InstantiationError`
  * explicit - `java.lang.InstantiationError`

I haven't had the chance to dig deeper into a solution–I'd appreciate any insight. 

To summarize, workarounds observed so far are:

* stay on Scala 2.13.1, before the new Vector implementation
* use `id-strategy = "incremental"`

## Stack Trace

```
Exception in thread "sbt-bg-threads-6" java.lang.InstantiationError: scala.collection.immutable.Vector
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor3.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.esotericsoftware.kryo.kryo5.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at com.esotericsoftware.kryo.kryo5.Kryo.newInstance(Kryo.java:1202)
	at io.altoo.serialization.kryo.scala.serializer.ScalaCollectionSerializer.read(ScalaCollectionSerializer.scala:33)
	at io.altoo.serialization.kryo.scala.serializer.ScalaCollectionSerializer.read(ScalaCollectionSerializer.scala:29)
	at com.esotericsoftware.kryo.kryo5.Kryo.readClassAndObject(Kryo.java:880)
	at io.altoo.serialization.kryo.scala.KryoSerializerBackend.fromBinary(KryoSerializerBackend.scala:61)
	at io.altoo.serialization.kryo.scala.KryoSerializer.fromBinaryInternal(KryoSerializer.scala:183)
	at io.altoo.serialization.kryo.scala.ScalaKryoSerializer.$anonfun$deserialize$1(ScalaKryoSerializer.scala:23)
	at scala.util.Try$.apply(Try.scala:217)
	at io.altoo.serialization.kryo.scala.ScalaKryoSerializer.deserialize(ScalaKryoSerializer.scala:23)
	at com.example.ScalaKryoVectorErrorExample$.delayedEndpoint$com$example$ScalaKryoVectorErrorExample$1(VectorSerializationExample.scala:23)
	at com.example.ScalaKryoVectorErrorExample$delayedInit$body.apply(VectorSerializationExample.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:42)
	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:98)
	at scala.App.$anonfun$main$1$adapted(App.scala:98)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at scala.App.main(App.scala:98)
	at scala.App.main$(App.scala:96)
	at com.example.ScalaKryoVectorErrorExample$.main(VectorSerializationExample.scala:9)
	at com.example.ScalaKryoVectorErrorExample.main(VectorSerializationExample.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1986)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1925)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

## Code Snippets

application.conf
```
scala-kryo-serialization {
  id-strategy = "explicit"
  kryo-initializer = "com.example.CustomKryoInitializer"
  resolve-subclasses = "true"
}
```

main
```scala
package com.example

import com.typesafe.config.ConfigFactory
import io.altoo.serialization.kryo.scala.serializer.ScalaKryo
import io.altoo.serialization.kryo.scala.{DefaultKryoInitializer, ScalaKryoSerializer}

import scala.util.{Failure, Success}

object VectorSerializationExample extends App {
  val config = ConfigFactory.load()
  val classLoader = Thread.currentThread().getContextClassLoader
  val serializer = new ScalaKryoSerializer(config, classLoader)

  val originalVector = Vector(1, 2, 3, 4, 5)
  println(s"Original vector: $originalVector")

  serializer.serialize(originalVector) match {
    case Success(serializedBytes) =>
      println(s"Serialized to ${serializedBytes.length} bytes")

      // set the type explicitly else
      // java.lang.ClassCastException: class scala.collection.immutable.Vector cannot be cast to class scala.runtime.Nothing
      serializer.deserialize[Vector[Int]](serializedBytes) match {
        case Success(deserializedVector) =>
          println(s"Deserialized vector: $deserializedVector")
        case Failure(e) =>
          println(s"Deserialization failed: ${e.getClass.getName}")
          e.printStackTrace()
      }

    case Failure(e) =>
      println(s"Serialization failed: ${e.getClass.getName}")
      e.printStackTrace()
  }
}

class CustomKryoInitializer extends DefaultKryoInitializer {
  override def postInit(kryo: ScalaKryo): Unit = {
    kryo.register(classOf[Vector[_]], 99)
  }
}
```

build.sbt
```
name := "kryo-vector-serialization-test"

version := "0.1"

val scala2131 = "2.13.1" // works
val scala2132 = "2.13.2" // error, new Vector impl introduced https://github.com/scala/scala/releases/tag/v2.13.2
val scala21315 = "2.13.15" // latest version has error too

scalaVersion := scala2131
crossScalaVersions := Seq(scala21315, scala2132, scala2131)

libraryDependencies ++= Seq(
  "io.altoo" %% "scala-kryo-serialization" % "1.2.0"
)
```

**Comment by nvollmar** [comment]
Thank you for bringing this up, we will look into that

**Comment by nvollmar** [comment]
It also works with id strategy `explicit` if you register the actual class used in the example:
```
kryo.register(Class.forName("scala.collection.immutable.Vector1"), 99)
```

**Comment by nvollmar** [comment]
So this was quite a long time ago, but we added with the release of Scala 2.13.2 an option config entry which provides the required registrations for vector subclasses:
https://github.com/altoo-ag/scala-kryo-serialization/blob/490b799a96a26bc6c39c1d6dd08e806052adf5cf/core/src/main/resources/reference.conf#L212

If you integrate that into your config serialization will work:
```
mappings = ${scala-kryo-serialization.optional-scala2_13-mappings}
```

I think with Vector the subclass resolver does not work as the sublcasses `Vector1` etc are private, where classes such as `Set1` are public with a private constructor.

**Comment by nvollmar** [comment]
To summarize:
* Use incremental (which also overwrites the class resolver)
* Use automatic without subclass resolution and/or vector registration
* Use automatic/explicit with proper registrations from `optional-scala2_13-mappings`

**Comment by michaelzg** [comment]
Thank you so much for the fast and thorough response! 
And also thank you and the team for maintaining this project!
Closing this issue.
